version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Unit Tests
          command: mvn test
      - run:
          name: Verify Build
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '#e.g. ./deploy.sh'

  upload-coverage:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test
      - codecov/upload:
          token: "CODECOV_TOKEN"  # Remove the ${} syntax

workflows:
  build-and-test:
    jobs:
      - test-java
      - deploy:
          requires:
            - test-java
          filters:
            branches:
              only: master

  upload-to-codecov:
    jobs:
      - upload-coverage
